import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {webcrypto} from 'node:crypto';
const code=readFileSync(new URL('../dist/app.js',import.meta.url),'utf8');
function setup(){const elements=new Map();const get=id=>{if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',value:'',querySelectorAll:()=>[],scrollIntoView:()=>{}});return elements.get(id);};let prints=0;const context={document:{getElementById:get,querySelectorAll:()=>[],body:{classList:{toggle:()=>{}}}},crypto:webcrypto,window:{print:()=>prints++},console};vm.createContext(context);vm.runInContext(code,context);return {run:s=>vm.runInContext(s,context),get,prints:()=>prints};}
test('final quiz covers two questions per concept and validates all answers',()=>{const {run}=setup();assert.equal(run('finalQuestions.length'),10);for(const id of ['salah','sawm','zakat','sadaqah','hajj'])assert.equal(run(`finalQuestions.filter(q=>q[0]==='${id}').length`),2);assert.equal(run('gradeFinal(finalQuestions.map(q=>q[3]))'),10);assert.throws(()=>run('gradeFinal(Array(10).fill(null))'));assert.throws(()=>run('gradeFinal(Array(10).fill(99))'));assert.throws(()=>run('gradeFinal([])'));});
test('certificate is blocked before completion and below 8; passing name is escaped',()=>{const {run,get,prints}=setup();run("state.view='exam';render()");assert.match(get('main').innerHTML,/Complete the learning journey first/);run("state.records.forEach(r=>r.done=true);examState.answers=finalQuestions.map(q=>q[3]);examState.answers[0]=(examState.answers[0]+1)%3;examState.answers[1]=(examState.answers[1]+1)%3;examState.answers[2]=(examState.answers[2]+1)%3;state.view='exam';render()");get('exam-submit').onclick();assert.equal(run('examState.score'),7);assert.doesNotMatch(get('main').innerHTML,/id="certificate-create"/);get('exam-retry').onclick();run('examState.answers=finalQuestions.map(q=>q[3]);examState.answers[0]=(examState.answers[0]+1)%3;examState.answers[1]=(examState.answers[1]+1)%3');get('exam-submit').onclick();assert.equal(run('examState.score'),8);assert.match(get('main').innerHTML,/id="certificate-create"/);get('certificate-name').value='';get('certificate-create').onclick();assert.equal(run('examState.certificate'),null);get('certificate-name').value='أسامة <img src=x onerror=alert(1)>';get('certificate-create').onclick();assert.match(get('main').innerHTML,/أسامة &lt;img/);assert.doesNotMatch(get('main').innerHTML,/<img src=x/);assert.match(get('main').innerHTML,/8 \/ 10/);get('certificate-print').onclick();assert.equal(prints(),1);get('certificate-back').onclick();get('exam-retry').onclick();assert.equal(run('examState.certificate'),null);assert.equal(run('examState.score'),null);});
